# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dpralte060b080/DPRALTE060B080_Msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DPRALTE060B080_Msg(genpy.Message):
  _md5sum = "9eb137a7320166026bceb0b1a0be23c5"
  _type = "dpralte060b080/DPRALTE060B080_Msg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32   velocity_left
int32   velocity_right
int32   odometry_left
int32   odometry_right
"""
  __slots__ = ['velocity_left','velocity_right','odometry_left','odometry_right']
  _slot_types = ['int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       velocity_left,velocity_right,odometry_left,odometry_right

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DPRALTE060B080_Msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.velocity_left is None:
        self.velocity_left = 0
      if self.velocity_right is None:
        self.velocity_right = 0
      if self.odometry_left is None:
        self.odometry_left = 0
      if self.odometry_right is None:
        self.odometry_right = 0
    else:
      self.velocity_left = 0
      self.velocity_right = 0
      self.odometry_left = 0
      self.odometry_right = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4i.pack(_x.velocity_left, _x.velocity_right, _x.odometry_left, _x.odometry_right))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.velocity_left, _x.velocity_right, _x.odometry_left, _x.odometry_right,) = _struct_4i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4i.pack(_x.velocity_left, _x.velocity_right, _x.odometry_left, _x.odometry_right))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.velocity_left, _x.velocity_right, _x.odometry_left, _x.odometry_right,) = _struct_4i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4i = struct.Struct("<4i")
